spring:
  application:
    name: loan-service-app
  datasource:
    url: jdbc:mysql://localhost:3306/loan_db
    username: root
    password: Chennai@330
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        show-sql: true
    generate-ddl: true
server:
  port: 8090
  
  
  
