server:
  port: 8090
 
spring:
  application:
    name: loan-service-app
  profiles:
    active: qa
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

        