spring:
  application:
    name: account-service-app
  datasource:
    url: jdbc:mysql://localhost:3306/account_db
    username: root
    password: Chennai@330
    driver-class-name: com.mysql.jdbc.Driver
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
server:
  port: 8085
  
  
  
