server:
  port: 8095
spring:
  application:
    name: card-service-app
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: qa
    
  datasource:
    url: jdbc:mysql://localhost:3309/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

   
  
management:
  endpoints:
    web:
      exposure:
        include: "*"