build:
  version: 1.0
  
  
accounts:
  message: "Welcome to EazyBank accounts related production APIs "
  contactDetails:
    name: "johnson - Developer in production"
    email: "johnson@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345