spring:
  config:
    activate: 
      on-profile: "prod"
  application:
    name: account-service-app
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085
  
build:
  version: 1.0
  
  
accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345